/*
You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
*/


class Solution {
    public char findTheDifference(String s, String t)
    {
        String tCut = t.substring(0, t.length()-1);       
     
        
        char[] sChars = s.toCharArray();
        char[] tChars = t.toCharArray();
        Arrays.sort(sChars);
        Arrays.sort(tChars);
        StringBuilder sBuilt = new StringBuilder();
        StringBuilder tBuilt = new StringBuilder();
        sBuilt.append(sChars);
        tBuilt.append(tChars);
        
        System.out.println(sBuilt);
        System.out.println(tBuilt);
        
        
        boolean found = false;  //false until found
        
        for(int i = 0; i < s.length(); i++)
        {
            if(sChars[i] != tChars[i])
            {
                return tChars[i];
            }
        }
        
        if(!found)
        {
            return tChars[tChars.length-1];
        }
        
        
        return ' ';
        
        //System.out.println("good");
        
        
    }
}
